version: '3.8'
services:
  postgres:
    image: postgres:15
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payments
  redis:
    image: redis:7
    ports: ["6379:6379"]
  localstack:
    image: localstack/localstack
    ports: ["4566:4566"]
    environment:
      SERVICES: sqs,sns